name: suv_ombor_monitoring
description: "ReservoSense - Water Storage Monitoring System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  
  # Core Architecture
  auto_route: ^10.2.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  injectable: ^2.5.2
  dartz: ^0.10.1
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  # Network & API
  dio: ^5.9.0
  retrofit: ^4.8.0
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^7.0.0
  internet_connection_checker: ^1.0.0+1
  infinite_scroll_pagination: ^4.0.0
  
  # Storage
  shared_preferences: ^2.5.3
  
  # UI & Styling
  sizer: ^3.1.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.3.2
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.2
  
  # Localization
  easy_localization: ^3.0.8
  
  # Utils
  logger: ^2.6.2
  restart_app: ^1.3.2
  
  # Permissions & Location
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  location: ^8.0.1
  device_info_plus: ^12.2.0
  google_maps_flutter: ^2.10.0
  
  # UI Components
  drag_and_drop_lists: ^0.4.2
  chips_choice: ^3.0.1
  easy_stepper: ^0.9.1
  flutter_slidable: ^4.0.3
  table_calendar: ^3.2.0
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  pin_code_fields: ^8.0.1
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  
  # Charts & Visualization
  syncfusion_flutter_charts: ^31.2.3
  fl_chart: ^1.1.1
  
  # PDF & Documents
  pdf: ^3.11.3
  printing: ^5.14.2
  syncfusion_flutter_pdf: ^31.2.3
  
  # Share
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Quality
  flutter_lints: ^5.0.0
  very_good_analysis: ^10.0.0
  
  # Code Generation
  build_runner: ^2.10.1
  injectable_generator: ^2.9.0
  retrofit_generator: ^10.1.1
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  auto_route_generator: ^10.2.5
  
  # Platform Specific
  google_maps_flutter_web: ^0.5.14+2
  syncfusion_flutter_xlsio: ^31.2.3
  
  # Development Tools
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.3
  change_app_package_name: ^1.3.0

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_icon.png"
  remove_alpha_ios: true
  
  # Android Adaptive Icons
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_icon.png"
  
  # Platform-specific icons (optional)
  # You can also specify different icons for different platforms
  # android: "assets/images/logo_icon_android.png"
  # ios: "assets/images/logo_icon_ios.png"
  
  # Min/Max SDK for Android
  min_sdk_android: 21
  
  # Web icon
  web:
    generate: true
    image_path: "assets/images/logo_icon.png"
    background_color: "#FFFFFF"
  
  # Windows icon
  windows:
    generate: true
    image_path: "assets/images/logo_icon.png"
  
  # macOS icon
  macos:
    generate: true
    image_path: "assets/images/logo_icon.png"

flutter:
  uses-material-design: true

  # Assets Configuration
  assets:
    # Images
    - assets/images/
    
    # Icons
    - assets/icons/
    # Lottie Animations
    - assets/lottie/
    
    # Translations
    - assets/translations/
    
    # JSON Data (if any)
    - assets/json/

  # Fonts Configuration (commented out until font files are added)
  # To use custom fonts:
  # 1. Download fonts from Google Fonts
  # 2. Place .ttf files in assets/fonts/
  # 3. Uncomment the fonts section below
  # 
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/playfair_display/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Medium.ttf
          weight: 500
    - family: Roboto flex
      fonts:
        - asset: assets/fonts/roboto_flex/RobotoFlex-Regular.ttf
          weight: 400

